-- ============================================================================
-- V2_471 : Larger identity cache for the SIX raw tables
--
-- The import now takes ids in blocks of 1000 from each table's own identity
-- sequence (ISEQ$$_nnn). The default identity cache is 20, which means Oracle
-- writes to its data dictionary every 20 ids (50 times per 1000-row batch).
-- CACHE 1000 makes that once per batch.
--
-- Only the cache changes: the column stays GENERATED BY DEFAULT AS IDENTITY,
-- the current value is kept, no data is touched. Safe to run on a live schema.
-- (Side effect of any sequence cache: ids may have gaps after a DB restart.
--  Ids are technical keys here, so gaps do not matter.)
-- ============================================================================
BEGIN
    FOR t IN (SELECT TABLE_NAME
                FROM USER_TAB_IDENTITY_COLS
               WHERE COLUMN_NAME = 'ID'
                 AND TABLE_NAME IN ('SIX_INSTRUMENTS', 'SIX_STRUCTURED', 'SIX_OPTION', 'SIX_TARGET'))
    LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || t.TABLE_NAME ||
                          ' MODIFY (ID GENERATED BY DEFAULT AS IDENTITY (CACHE 1000))';
    END LOOP;
END;
/
