package com.bnpp.regliss.importer.six.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import javax.annotation.PostConstruct;
import javax.persistence.Column;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.regex.Pattern;

import com.bnpp.regliss.utils.EntityUtils;

// TODO: re-add project import for: ReglissBatchProfile

/**
 * Writes SIX raw rows (SIX_INSTRUMENTS / SIX_STRUCTURED / SIX_OPTION + SIX_TARGET)
 * with plain JDBC batch INSERTs.
 *
 * WHY: the entities use GenerationType.IDENTITY. With IDENTITY, Hibernate must send
 * every INSERT on its own to read the generated id back, so JPA can never batch these
 * tables: 1 lakh parents + their targets = several lakh single-row round trips per file.
 *
 * HOW:
 *  - Ids come from the table's OWN identity sequence (the ISEQ$$_nnn sequence Oracle
 *    created for "ID ... GENERATED BY DEFAULT AS IDENTITY"). One query per batch:
 *        SELECT "OWNER"."ISEQ$$_nnn".NEXTVAL FROM DUAL CONNECT BY LEVEL <= 1000
 *    Same sequence Oracle uses itself, so ids can never collide with rows inserted any
 *    other way, and no new sequence or table is needed.
 *  - Parent ids are known before the INSERT, so the SIX_TARGET children are batched too.
 *  - Parents + children of one batch commit together in a NEW transaction: a failed batch
 *    leaves nothing half-written.
 *  - The INSERT column list is read once per entity class from its existing JPA
 *    annotations (@Table, @Column, @JoinColumn). Entities are NOT changed. If a field
 *    cannot be mapped the writer stops with a clear message instead of skipping a column.
 *  - Text longer than its column is cut exactly like today: JPA runs
 *    TruncateStringFieldsListener (@PrePersist) on every AbstractSimpleEntity, which calls
 *    EntityUtils.truncateStringFields(entity). This writer bypasses JPA, so it calls the
 *    same method itself for every parent and SIX_TARGET row before binding.
 */
@Component
@ReglissBatchProfile
@Slf4j
public class SixJdbcBulkWriter {

    private static final Pattern SQL_NAME = Pattern.compile("^[A-Z][A-Z0-9_$#]{0,127}$");

    /** Max rows per executeBatch() round trip (children can outnumber parents). */
    private static final int JDBC_CHUNK = 1000;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PlatformTransactionManager transactionManager;

    @Autowired
    private Environment environment;

    private TransactionTemplate newTx;

    private final Map<Class<?>, TableMapping> mappings = new ConcurrentHashMap<>();
    private final Map<String, String> idSequences = new ConcurrentHashMap<>();

    @PostConstruct
    void init() {
        newTx = new TransactionTemplate(transactionManager);
        newTx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    }

    /**
     * Inserts one batch of parents and all their SIX_TARGET children in one new transaction.
     *
     * @param parents       mapped entities of one batch (InstrumentFile / StructuredFile / OptionsFile)
     * @param listId        LIST_ID of every parent
     * @param versionId     VERSION_ID of every parent
     * @param childrenOf    e.g. InstrumentFile::getSixTargets
     * @param childFkColumn SIX_TARGET column pointing to the parent: SIX_INSTRU_ID / SIX_STRUCT_ID / SIX_OPT_ID
     * @return number of SIX_TARGET rows written
     */
    public <P> int insertBatch(List<P> parents, long listId, long versionId,
                               Function<P, ? extends Collection<?>> childrenOf, String childFkColumn) {
        if (parents.isEmpty()) {
            return 0;
        }
        final TableMapping parentMap = mappingFor(parents.get(0).getClass());
        final List<Object> children = new ArrayList<>();
        final List<P> childParent = new ArrayList<>();
        collectChildren(parents, childrenOf, children, childParent);

        final TableMapping childMap = children.isEmpty() ? null : mappingFor(children.get(0).getClass());
        final String parentSeq = idSequenceFor(parentMap.table);
        final String childSeq = childMap == null ? null : idSequenceFor(childMap.table);

        // Same truncation as TruncateStringFieldsListener (@PrePersist) does for JPA saves:
        // String @Column fields longer than their length (UTF-8 bytes) are cut, not rejected.
        parents.forEach(EntityUtils::truncateStringFields);
        children.forEach(EntityUtils::truncateStringFields);

        Integer written = newTx.execute(status -> {
            // 1. parent ids + parent rows (LIST_ID / VERSION_ID forced to this import's values)
            List<Long> parentIds = nextIds(parentSeq, parents.size());
            Map<Object, Long> idByParent = new IdentityHashMap<>(parents.size() * 2);
            for (int i = 0; i < parents.size(); i++) {
                parentMap.setId(parents.get(i), parentIds.get(i));
                idByParent.put(parents.get(i), parentIds.get(i));
            }
            batchInsert(parentMap, parents, parentIds, (row, col) -> listOrVersionId(col, listId, versionId));

            // 2. child ids + child rows, FK set from the parent id
            if (childMap != null) {
                List<Long> childIds = nextIds(childSeq, children.size());
                List<Long> fk = new ArrayList<>(children.size());
                for (int i = 0; i < children.size(); i++) {
                    childMap.setId(children.get(i), childIds.get(i));
                    fk.add(idByParent.get(childParent.get(i)));
                }
                batchInsert(childMap, children, childIds, (row, col) -> childFkColumn.equals(col) ? fk.get(row) : null);
            }
            return children.size();
        });
        return written == null ? 0 : written;
    }

    /** Flattens the SIX_TARGET children of the batch; childParent.get(i) is the parent of children.get(i). */
    private static <P> void collectChildren(List<P> parents, Function<P, ? extends Collection<?>> childrenOf,
                                            List<Object> children, List<P> childParent) {
        for (P parent : parents) {
            Collection<?> kids = childrenOf.apply(parent);
            if (kids == null) {
                continue;
            }
            for (Object kid : kids) {
                if (kid != null) {
                    children.add(kid);
                    childParent.add(parent);
                }
            }
        }
    }

    /** LIST_ID and VERSION_ID of every parent row are forced to this import's values. */
    private static Object listOrVersionId(String column, long listId, long versionId) {
        if ("LIST_ID".equals(column)) {
            return listId;
        }
        if ("VERSION_ID".equals(column)) {
            return versionId;
        }
        return null;
    }

    /**
     * Removes every row of one version (SIX_TARGET rows go with them: ON DELETE CASCADE in V2_470).
     * Used when an import fails, so no half-loaded version is left behind.
     */
    public int deleteVersion(Class<?> parentEntity, long versionId) {
        String sql = "DELETE FROM " + mappingFor(parentEntity).table + " WHERE VERSION_ID = ?";   // table name checked by sqlName()
        Integer n = newTx.execute(status -> jdbcTemplate.update(sql, versionId));
        return n == null ? 0 : n;
    }

    // ------------------------------------------------------------------ internals

    /** Returns a value that replaces the entity field for this row/column, or null to use the field. */
    private interface RowValues {
        Object valueFor(int row, String column);
    }

    private void batchInsert(TableMapping map, List<?> rows, List<Long> ids, RowValues forced) {
        for (int from = 0; from < rows.size(); from += JDBC_CHUNK) {
            final int start = from;
            final int end = Math.min(from + JDBC_CHUNK, rows.size());
            jdbcTemplate.batchUpdate(map.insertSql, new BatchPreparedStatementSetter() {
                @Override
                public void setValues(PreparedStatement ps, int i) throws SQLException {
                    int row = start + i;
                    Object entity = rows.get(row);
                    ps.setLong(1, ids.get(row));
                    int p = 2;
                    for (ColumnMapping c : map.columns) {
                        Object value = forced.valueFor(row, c.column);
                        if (value != null) {
                            ps.setLong(p++, ((Number) value).longValue());
                        } else {
                            c.bind(ps, p++, entity);
                        }
                    }
                }

                @Override
                public int getBatchSize() {
                    return end - start;
                }
            });
        }
    }

    private List<Long> nextIds(String sequence, int count) {
        List<Long> ids = jdbcTemplate.queryForList(
                "SELECT " + sequence + ".NEXTVAL FROM DUAL CONNECT BY LEVEL <= ?", Long.class, count);
        if (ids.size() != count) {
            throw new IllegalStateException(sequence + " returned " + ids.size() + " ids, expected " + count);
        }
        return ids;
    }

    /**
     * The table's identity sequence, e.g. "REGLISS"."ISEQ$$_91833". Looked up once.
     * Override with six.import.id-sequence.<TABLE>=OWNER.SEQ_NAME if the application
     * user is not the table owner (synonyms).
     */
    private String idSequenceFor(String table) {
        return idSequences.computeIfAbsent(table, t -> {
            String override = environment.getProperty("six.import.id-sequence." + t);
            if (override != null && !override.trim().isEmpty()) {
                return qualified(override.trim().toUpperCase(Locale.ROOT));
            }
            List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                    "SELECT OWNER, SEQUENCE_NAME FROM ALL_TAB_IDENTITY_COLS" +
                    " WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AND TABLE_NAME = ? AND COLUMN_NAME = 'ID'", t);
            if (rows.size() != 1) {
                throw new IllegalStateException("No identity sequence found for " + t + ".ID in the current schema;"
                        + " set six.import.id-sequence." + t + "=OWNER.SEQUENCE_NAME");
            }
            String seq = qualified(rows.get(0).get("OWNER") + "." + rows.get(0).get("SEQUENCE_NAME"));
            log.info("SIX import: {} ids come from {}", t, seq);
            return seq;
        });
    }

    private static String qualified(String ownerDotName) {
        String[] parts = ownerDotName.split("\\.");
        StringBuilder sb = new StringBuilder();
        for (String part : parts) {
            if (!SQL_NAME.matcher(part).matches()) {
                throw new IllegalArgumentException("Bad sequence name: " + ownerDotName);
            }
            sb.append(sb.length() == 0 ? "" : ".").append('"').append(part).append('"');
        }
        return sb.toString();
    }

    private TableMapping mappingFor(Class<?> type) {
        return mappings.computeIfAbsent(type, TableMapping::new);
    }

    /**
     * Column list + INSERT statement for one entity class, built once from its JPA annotations.
     *
     * Security (Sonar S3011 "accessibility bypass"): fields are only inspected for their annotations;
     * values are read and the id is set through the entities' PUBLIC getters/setters (Lombok
     * @Getter/@Setter), never with setAccessible(true).
     */
    static final class TableMapping {
        final String table;
        final Method idSetter;
        final List<ColumnMapping> columns = new ArrayList<>();
        final String insertSql;

        TableMapping(Class<?> type) {
            this.table = tableName(type);
            Method idSet = null;
            for (Class<?> c : hierarchyTopDown(type)) {
                for (Field f : c.getDeclaredFields()) {
                    if (!isPersistent(f)) {
                        continue;
                    }
                    if (f.isAnnotationPresent(Id.class)) {
                        idSet = publicMethod(type, accessorName("set", f), f.getType());
                    } else {
                        ColumnMapping column = columnFor(type, c, f, table);
                        if (column != null) {
                            columns.add(column);      // null = insertable = false: not written, as with JPA
                        }
                    }
                }
            }
            if (idSet == null) {
                throw new IllegalStateException(type.getName() + " has no @Id field");
            }
            this.idSetter = idSet;
            this.insertSql = insertSql(table, columns);
            log.info("SIX import: {} -> {} ({} columns)", type.getSimpleName(), table, columns.size() + 1);
        }

        void setId(Object entity, Long id) {
            try {
                idSetter.invoke(entity, id);
            } catch (ReflectiveOperationException e) {
                throw new IllegalStateException("Cannot set the id of " + entity.getClass().getSimpleName(), e);
            }
        }

        private static String tableName(Class<?> type) {
            Table t = type.getAnnotation(Table.class);
            if (t == null || t.name().isEmpty()) {
                throw new IllegalStateException(type.getName() + " has no @Table(name=...)");
            }
            return sqlName(t.name(), type.getName());
        }

        private static List<Class<?>> hierarchyTopDown(Class<?> type) {
            List<Class<?>> hierarchy = new ArrayList<>();
            for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
                hierarchy.add(c);
            }
            Collections.reverse(hierarchy);
            return hierarchy;
        }

        private static boolean isPersistent(Field f) {
            int mod = f.getModifiers();
            return !(Modifier.isStatic(mod) || Modifier.isTransient(mod) || f.isSynthetic()
                    || f.isAnnotationPresent(Transient.class)
                    || f.isAnnotationPresent(OneToMany.class)
                    || f.isAnnotationPresent(ManyToMany.class));
        }

        private static ColumnMapping columnFor(Class<?> type, Class<?> declaring, Field f, String table) {
            Column col = f.getAnnotation(Column.class);
            JoinColumn join = f.getAnnotation(JoinColumn.class);
            boolean relation = f.isAnnotationPresent(ManyToOne.class) || f.isAnnotationPresent(OneToOne.class);
            if (col != null) {
                return col.insertable()
                        ? new ColumnMapping(sqlName(columnName(col.name(), f), f.getName()), f, readerFor(type, f), false)
                        : null;
            }
            if (relation && join != null) {
                return join.insertable()
                        ? new ColumnMapping(sqlName(columnName(join.name(), f), f.getName()), f, readerFor(type, f), true)
                        : null;
            }
            throw new IllegalStateException("Cannot map " + declaring.getSimpleName() + "." + f.getName()
                    + " for insert into " + table + ": add @Column(name=...) or @Transient");
        }

        private static Method readerFor(Class<?> type, Field f) {
            String prefix = f.getType() == boolean.class ? "is" : "get";
            return publicMethod(type, accessorName(prefix, f));
        }

        private static String insertSql(String table, List<ColumnMapping> columns) {
            StringBuilder cols = new StringBuilder("ID");
            StringBuilder qs = new StringBuilder("?");
            for (ColumnMapping c : columns) {
                cols.append(", ").append(c.column);
                qs.append(", ?");
            }
            return "INSERT INTO " + table + " (" + cols + ") VALUES (" + qs + ")";
        }

        private static String columnName(String annotated, Field f) {
            return (annotated == null || annotated.isEmpty()) ? f.getName() : annotated;
        }
    }

    /** Lombok accessor name: get/set/is + field name with its first letter in upper case. */
    private static String accessorName(String prefix, Field f) {
        String n = f.getName();
        return prefix + Character.toUpperCase(n.charAt(0)) + n.substring(1);
    }

    private static Method publicMethod(Class<?> type, String name, Class<?>... params) {
        try {
            return type.getMethod(name, params);          // public methods only, no accessibility change
        } catch (NoSuchMethodException e) {
            throw new IllegalStateException(type.getSimpleName() + " has no public " + name + "(): add @Getter/@Setter", e);
        }
    }

    /**
     * Security (Fortify "SQL Injection"): table and column names come from the entity annotations,
     * never from input, and are additionally checked against a strict identifier pattern before
     * they are put into an SQL statement. All values are bound as parameters.
     */
    private static String sqlName(String raw, String where) {
        String n = raw.replace("\"", "").toUpperCase(Locale.ROOT);
        if (!SQL_NAME.matcher(n).matches()) {
            throw new IllegalStateException("Unsupported SQL name '" + n + "' (" + where + ")");
        }
        return n;
    }

    /** Reads one property and binds it with a stable JDBC type (keeps Oracle batches from splitting). */
    static final class ColumnMapping {
        final String column;
        final Class<?> type;
        final Method getter;
        final Method relatedIdGetter;     // getId() of the related entity, resolved once (FK columns only)
        final EnumType enumType;

        ColumnMapping(String column, Field field, Method getter, boolean foreignKey) {
            this.column = column;
            this.type = field.getType();
            this.getter = getter;
            this.relatedIdGetter = foreignKey ? publicMethod(field.getType(), "getId") : null;   // declared type: works for Hibernate proxies too
            Enumerated en = field.getAnnotation(Enumerated.class);
            this.enumType = en == null ? EnumType.ORDINAL : en.value();
        }

        void bind(PreparedStatement ps, int pos, Object entity) throws SQLException {
            Object value = read(getter, entity, column);
            if (relatedIdGetter != null) {
                bindForeignKey(ps, pos, value);
            } else {
                bindValue(ps, pos, value);
            }
        }

        private void bindForeignKey(PreparedStatement ps, int pos, Object related) throws SQLException {
            Object id = related == null ? null : read(relatedIdGetter, related, column);
            if (id == null) {
                ps.setNull(pos, Types.NUMERIC);
            } else {
                ps.setLong(pos, ((Number) id).longValue());
            }
        }

        private void bindValue(PreparedStatement ps, int pos, Object value) throws SQLException {
            if (value == null) {
                ps.setNull(pos, sqlType(type));
            } else if (value instanceof String) {
                ps.setString(pos, (String) value);
            } else if (value instanceof Enum) {
                bindEnum(ps, pos, (Enum<?>) value);
            } else if (value instanceof Boolean) {
                ps.setInt(pos, Boolean.TRUE.equals(value) ? 1 : 0);
            } else if (value instanceof java.util.Date && !(value instanceof java.sql.Date)) {
                ps.setTimestamp(pos, new Timestamp(((java.util.Date) value).getTime()));
            } else {
                ps.setObject(pos, value);
            }
        }

        private void bindEnum(PreparedStatement ps, int pos, Enum<?> e) throws SQLException {
            if (enumType == EnumType.STRING) {
                ps.setString(pos, e.name());
            } else {
                ps.setInt(pos, e.ordinal());
            }
        }

        private static Object read(Method getter, Object target, String column) throws SQLException {
            try {
                return getter.invoke(target);
            } catch (ReflectiveOperationException e) {
                throw new SQLException("Cannot read " + getter.getName() + " for column " + column, e);
            }
        }

        private static int sqlType(Class<?> t) {
            if (t == String.class || t.isEnum()) {
                return Types.VARCHAR;
            }
            if (Number.class.isAssignableFrom(t) || t == Boolean.class) {
                return Types.NUMERIC;
            }
            if (java.util.Date.class.isAssignableFrom(t) || t.getName().startsWith("java.time.")) {
                return Types.TIMESTAMP;
            }
            return Types.VARCHAR;
        }
    }
}
