-- ============================================================================
-- ROLLBACK for V2_471__six_import_identity_cache.sql
--
-- NOT a Flyway migration: keep this file OUTSIDE db/migration. Run it manually
-- (DBA) only if V2_471 must be undone.
--
-- What it does: puts the identity cache of the 4 SIX tables back to 20, the
-- Oracle default those tables had before V2_471 (V2_458/459/460/470 create the
-- ID columns without a CACHE clause). Run db/checks/check_identity_cache.sql
-- BEFORE the deployment; if a table showed a value other than 20, use that value.
--
-- Safe: no data is touched, the current id value is kept, can run while the
-- application is up, can run more than once.
-- ============================================================================
BEGIN
    FOR t IN (SELECT TABLE_NAME
                FROM USER_TAB_IDENTITY_COLS
               WHERE COLUMN_NAME = 'ID'
                 AND TABLE_NAME IN ('SIX_INSTRUMENTS', 'SIX_STRUCTURED', 'SIX_OPTION', 'SIX_TARGET'))
    LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || t.TABLE_NAME ||
                          ' MODIFY (ID GENERATED BY DEFAULT AS IDENTITY (CACHE 20))';
    END LOOP;
END;
/

-- Optional: only if the whole release is rolled back and V2_471 must run again
-- at the next deployment, remove its Flyway history row.
-- DELETE FROM flyway_schema_history WHERE version = '2.471';
-- COMMIT;
