#Properties file for internal spring configuration, we dont expose this configuration to the user
#Loaded together with config-app.properties resolved from CONFIG_PARAMS
#JPA AND HIBERNATE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:p6spy:oracle:thin:@//D-11672-P.fr.net.intra:1521/D11672AP10
#spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
springdoc.api-docs.path=/v2/api-docs

#only database connection properties that will be tokenized here
# config-app*.properties are loaded last at runtime and we can not override them with jvm.options or env vars to be able to start local env
spring.datasource.url={{ lstToken.REGLISS_JDBC_URL }}
spring.datasource.username={{ lstToken.REGLISS_JDBC_USER_NAME }}
spring.datasource.password={{ lstToken.DBPASSWORD }}

user.lastConnection.inactive.days=180
user.ignore.profiles=init,sys,test
refog.host=https://ws-qds.group.echonet
refog.user=cn=user_CPS
refog.pass=Saxsi?32
refog.url.searchText.length=2083
fircoExport.crypto.regex=[ @.%-!#/,:;|]
fircoExport.crypto.idNotes=ARB,BCH,BNB,BSC,BSV,BTC,BTG,DASH,ETC,ETH,LTC,SOL,TRX,USDC,USDT,XBT,XMR,XRP,XVG,ZEC,Adresses de portefeuille de chaine de blocs connues,Known blockchain wallet addresses
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=7200000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.leak-detection-threashold=63000

jwt.backend.secret={{ lstToken.DBPASSWORD01 }}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
#hibernate.jpa.compliance.global_id_generators=false TODO
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.jdbc.fetch_size=${automatic.import.page.size}
spring.jpa.properties.hibernate.jdbc.batch_size=${automatic.import.page.size}
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jpa.compliance.global_id_generators=false

logging.level.org.springframework.web=debug


server.port=9080
server.servlet.context-path=/regliss-app

#spring mvc
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


#Activate flyway only if flyway profile is explicitly activated
spring.flyway.enabled=false

##server.error.whitelabel.enabled=false
##management.endpoints.enabled-by-default=false
#management.endpoint.health.enabled=true
#management.endpoint.health.show-details=when_authorized
##management.health.defaults.enabled=false
#management.health.db.enabled=true
#management.health.diskspace.enabled=true
#
#allowed.unsecured.endpoints=/actuator/health
#management.endpoints.web.exposure.include=*
#management.endpoints.jmx.exposure.include=health

management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.health.show-details=when_authorized
management.health.defaults.enabled=false
management.health.db.enabled=false
management.health.diskspace.enabled=true
management.auditevents.enabled=false
allowed.unsecured.endpoints=/actuator/health

spring.jpa.properties.javax.persistence.validation.mode=none

#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=TRACE
spring.main.allow-circular-references=true

six.exclusion.list=959
six.cmic.list=951
six.e014071.list=235
six.db.batch = 1000
allow.six.file.integration = INSTR,STRUCT
six.file.prefix = GSM
six.file.specific.code = 203
automatic.import.db.thread.pool.size = 4
