#This properties file mirrors config-app.properties but replaces ARA token values with normal values so local env can start

#should be isutf8 in prod
file.isutf8.command.base=${project.basedir}\\src\\main\\scripts\\isutf8.bat
file.download.days.before.expiration=180

pgp.command.base=${project.basedir}\\src\\main\\scripts\\pgp.bat
gpg.command.base=gpg
regliss.key.userid=D14974E
gpg.logFile= C:/Users/f72337/GPGTEST/FILE.log
fircoExport.crypto.idNotes=ARB,BCH,BNB,BSC,BSV,BTC,BTG,DASH,ETC,ETH,LTC,SOL,TRX,USDC,USDT,XBT,XMR,XRP,XVG,ZEC,Adresses de portefeuille de chaine de blocs connues,Known blockchain wallet addresses
fircoExport.crypto.regex=[ @.%-!#/,:;|]

cft.gtw.hostname.SIX={{ lstToken.CFT_GTW_HOSTNAME_SIX }}
cft.gtw.idf.six={{ lstToken.CFT_GTW_IDF_SIX  }}
cft.gtw.part.six={{ lstToken.CFT_GTW_PART_SIX  }}
cft.gtw.path_to_file.six={{ lstToken.CFT_GTW_PATH_TO_FILE_SIX  }}
cft.gtw.gmt.SIX=GMT+02:00
cft.gtw.hostpath.SIX={{ lstToken.CFT_GTW_HOSTPATH_SIX  }}
cft.gtw.idf.SIX.LISTFILE={{ lstToken.CFT_GTW_IDF_SIX_LISTFILES  }}
cft.gtw.idf.SIX.PATTERNRETREIVE={{ lstToken.CFT_GTW_IDF_SIX_PATTERN_RETREIVE  }}
cft.gtw.SIX.FilenameCorrection={{ lstToken.CFT_GTW_SIX_FILENAMECORRECTION  }}
cft.gtw.hostpath.SIXArchive={{ lstToken.CFT_GTW_HOSTPATH_SIXArchive  }}


user.lastConnection.inactive.days=180
user.ignore.profiles=init,sys,test
refog.host=https://ws-qds.group.echonet
refog.user=cn=user_CPS
refog.pass=Saxsi?32
refog.url.searchText.length=2083
#should be CFTUTIL in prod
cft.command.base=c:/workspace/_core/CFTUTIL-mock.bat
cft.process.log.folder=C:/workspace/_regliss/cft_logs
cft.send.command.base=cmd.exe /c ${project.basedir}/src/main/scripts/cft-send-mock.bat
cft.push.folder.base=c:/workspace/_regliss
cft.log.file=${project.basedir}/src/main/script/logfile.txt
cft.gtw.hostname.WATCHLIST=S04917N5GELGETP1
cft.gtw.hostname.WATCHLIST_EXTRA=S04917N5GELGETP1
cft.gtw.hostname.CORE=S04917N5GELGETP1
cft.gtw.hostname.AME=S04917N5GELGETP1
cft.gtw.path_to_file=${project.basedir}
cft.gtw.idf.WATCHLIST=IDFWATCHLIST
cft.gtw.idf.AME=IDFAME
cft.gtw.idf.WATCHLIST_EXTRA=IDFWLEXTRA
cft.gtw.part.WATCHLIST=PARTWATCHLIST
cft.gtw.part.CORE=PARTCORE
cft.gtw.part.WATCHLIST_EXTRA=PARTWLEXTRA

users.banned=test

task.check.user.download.rights.cron=0 0/1 * * * *

authentication.high.index.html.url=http://localhost:9080/regliss-high/app/index.html
external.element.detail.context=regliss-external
external.element.detail.html.url=http://localhost:9080/${external.element.detail.context}/app/index.html


application.index.html.url=http://localhost:9080/regliss-app/app/index.html


url.vigilance = http://vigilance.fr.net.intra
url.echonet = http://echonet.fr.net.intra
url.high.authentication = http://localhost:9080/regliss-high/saml/login

task.cft_sent_files_cleaner.interval = 50000
task.dj_import.cron = 0 0/1 07-23 * * *
task.users_sync.cron = 0 0 8 1,15 * *
task.purgeOrphanRecords.cron = 0 0 3 * * *

export.add.mod.sup.excel.template=${project.basedir}/src/main/resources/ADD_MOD_SUPP_Template_v1.0.xlsx
export.add.mod.sup.excel.name=ADDSUPPMOD

spring.mail.host=smtp-appli-ema.staging.echonet.net.intra
spring.mail.port=25
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=15000
mail.from=adrian.rosu@dev.fr
#new ema configuration
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.username=emanp.group.regliss-dev@noprod.bnpparibas.com
spring.mail.password=x6AFh3M+
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


automatic.import.IN.directory=${project.basedir}/src/test/resources/importer/dj/in
automatic.import.IGNORE.directory=${project.basedir}/src/test/resources/importer/dj/ignore
automatic.import.ERROR.directory=${project.basedir}/src/test/resources/importer/dj/error
automatic.import.six.IN.directory=${project.basedir}/src/test/resources/importer/six/in
automatic.import.six.IGNORE.directory=${project.basedir}/src/test/resources/importer/six/ignore
automatic.import.six.ERROR.directory=${project.basedir}/src/test/resources/importer/six/error

automatic.import.transformer.DOW_JONES_WATCHLIST=file:///${basedir}/src/main/resources/dow-jones-watchlist-xslt.xml
automatic.import.transformer.DOW_JONES_CORE=file:///${basedir}/src/main/resources/dow-jones-core-xslt.xml
automatic.import.transformer.CUSTOM_AUTOMATIC=file:///${basedir}/src/main/resources/custom-automatic-xslt.xml
automatic.import.transformer.SIX_INSTRUMENT=file:///${basedir}/src/main/resources/instruments-xslt.xml
automatic.import.transformer.SIX_STRUCTURE=file:///${basedir}/src/main/resources/structured-xslt.xml
automatic.import.transformer.SIX_OPTION=file:///${basedir}/src/main/resources/options-xslt.xml
automatic.import.xsd.DOW_JONES_WATCHLIST=${basedir}/src/main/resources/PFA_XSD_22-Dec-07.xsd
automatic.import.xsd.DOW_JONES_CORE=${basedir}/src/main/resources/Dow_Jones_Sanction_Alert_XML_Schema.xsd
automatic.import.xsd.CUSTOM_AUTOMATIC=${basedir}/src/main/resources/custom_automatic_validator.xsd
automatic.import.xsd.SIX_INSTRU_AUTOMATIC=${basedir}/src/main/resources/SSM_Instruments_1.4a.xsd
automatic.import.xsd.SIX_STRUCT_AUTOMATIC=${basedir}/src/main/resources/SSM_Structured_1.4a.xsd
automatic.import.xsd.SIX_OPTIONS_AUTOMATIC=${basedir}/src/main/resources/SSM_Options_1.4a.xsd
automatic.import.autoconfirm.threshold.percentage=400

temp.file.folder=C:/workspace/tmp
shared.file.folder=C:/workspace/shared
shared.file.folder.import=manual.import

spring.servlet.multipart.max-file-size=2560MB
spring.servlet.multipart.max-request-size=2560MB
is.production.environment=false

deployed.environment=LOCAL

jasperreports.location=file:///${basedir}/src/main/resources/jasperreports/

six.exclusion.list=959
six.cmic.list=951
six.e014071.list=235
six.db.batch = 1000
allow.six.file.integration = INSTR,STRUCT
six.file.prefix = GSM
six.file.specific.code = 203
automatic.import.db.thread.pool.size = 4
