DECLARE
    v_cnt NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_cnt
      FROM USER_TABLES
     WHERE UPPER(TABLE_NAME) = 'SIX_FILTERED_POLLER';

    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE "SIX_FILTERED_POLLER" CASCADE CONSTRAINTS';
    END IF;
END;
/

DECLARE
    v_cnt NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_cnt
      FROM USER_SEQUENCES
     WHERE UPPER(SEQUENCE_NAME) = 'SIX_FILTERED_POLLER_SEQ';

    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP SEQUENCE "SIX_FILTERED_POLLER_SEQ"';
    END IF;
END;
/
