DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;   
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'FILTERED_SIX_TARGET_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE FILTERED_SIX_TARGET_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'FILTERED_SIX_TARGET';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE FILTERED_SIX_TARGET (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                SIX_INSTRU_ID                  NUMBER(19,0),
                SIX_STRUCT_ID                  NUMBER(19,0),
                SIX_OPT_ID                     NUMBER(19,0),
                TARGET                         VARCHAR2(255 CHAR),
                REGIME                         VARCHAR2(255 CHAR),
                LEGAL_BASIS                    VARCHAR2(255 CHAR),
                SANCTIONED                     VARCHAR2(255 CHAR),
                REASON_FOR_CHANGE              VARCHAR2(2000 CHAR),
                SANCTIONS_RATIONALE            VARCHAR2(4000 CHAR),

                CONSTRAINT PK_FILTERED_SIX_TARGET PRIMARY KEY (ID),

                CONSTRAINT FK_FILTERED_SIX_TARGET_INSTRU
                FOREIGN KEY (SIX_INSTRU_ID)
                REFERENCES FILTERED_SIX_INSTRUMENTS (ID)
                ON DELETE CASCADE,

                CONSTRAINT FK_FILTERED_SIX_TARGET_STRUCT
                FOREIGN KEY (SIX_STRUCT_ID)
                REFERENCES FILTERED_SIX_STRUCTURED (ID)
                ON DELETE CASCADE,

                CONSTRAINT FK_FILTERED_SIX_TARGET_OPTIONS
                FOREIGN KEY (SIX_OPT_ID)
                REFERENCES FILTERED_SIX_OPTION (ID)
                ON DELETE CASCADE
            )';
    END IF; 
END;
/
