DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_SUB_FILTERS_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_SUB_FILTERS_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_SUB_FILTERS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_SUB_FILTERS (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                SIX_SUBFILTER_INDEX      NUMBER(19),
                SIX_SUBFILTER_NAME       VARCHAR2(255),
                SIX_FILTER_ID            NUMBER(19),
                IS_DELETED               NUMBER(1)    DEFAULT 0,
                IS_NESTED_FILTER         NUMBER(1)    DEFAULT 0,

                CONSTRAINT PK_SIX_SUB_FILTERS     PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_SUB_FILTERS_ID
                    FOREIGN KEY (SIX_FILTER_ID)
                    REFERENCES SIX_FILTERS (ID)
            )';
    END IF;
END;
/
