DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_rows         NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_FIELD_TYPE_FILTER_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_FIELD_TYPE_FILTER_SEQ
             START WITH 1
             INCREMENT BY 1
             NOORDER
             NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_FIELD_TYPE_FILTER';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_FIELD_TYPE_FILTER (
                            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                            FILTER_TYPE               VARCHAR2(255),
                            FIELD_NAME                VARCHAR2(255),
                            CONSTRAINT PK_SIX_FIELD_TYPE_FILTER   PRIMARY KEY (ID)
            )';
    END IF;  
   
END;
/
