DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_index_exists1 NUMBER;
    v_index_exists2 NUMBER;
    v_index_exists3 NUMBER;
    v_index_exists4 NUMBER;

BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_TARGET_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_TARGET_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_TARGET';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_TARGET (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                SIX_INSTRU_ID                  NUMBER(19,0),
                SIX_STRUCT_ID                  NUMBER(19,0),
                SIX_OPT_ID                     NUMBER(19,0),
                TARGET                         VARCHAR2(255 CHAR),
                REGIME                         VARCHAR2(255 CHAR),
                LEGAL_BASIS                    VARCHAR2(255 CHAR),
                SANCTIONED                     VARCHAR2(255 CHAR),
                STATUS                         VARCHAR2(255 CHAR),
                SANCTION_FLAG_CHANGED          VARCHAR2(255 CHAR),
                REASON_FOR_CHANGE              VARCHAR2(2000 CHAR),
                SANCTIONS_RATIONALE            VARCHAR2(4000 CHAR),

                CONSTRAINT PK_SIX_TARGET PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_TARGET_INSTRU
                FOREIGN KEY (SIX_INSTRU_ID)
                REFERENCES SIX_INSTRUMENTS (ID)
                ON DELETE CASCADE,

                CONSTRAINT FK_SIX_TARGET_STRUCT
                FOREIGN KEY (SIX_STRUCT_ID)
                REFERENCES SIX_STRUCTURED (ID)
                ON DELETE CASCADE,

                CONSTRAINT FK_SIX_TARGET_OPTIONS
                FOREIGN KEY (SIX_OPT_ID)
                REFERENCES SIX_OPTION (ID)
                ON DELETE CASCADE
            )';
    END IF;

    SELECT COUNT(*) INTO v_index_exists1
               FROM USER_INDEXES
              WHERE UPPER(INDEX_NAME) = 'IDX_SIX_TARGET_INSTR_ID';
          IF v_index_exists1 = 0 THEN
              EXECUTE IMMEDIATE
              'CREATE INDEX IDX_SIX_TARGET_INSTR_ID ON SIX_TARGET (SIX_INSTRU_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists2
               FROM USER_INDEXES
              WHERE UPPER(INDEX_NAME) = 'IDX_SIX_TARGET_STRUCT_ID';
          IF v_index_exists2 = 0 THEN
              EXECUTE IMMEDIATE
              'CREATE INDEX IDX_SIX_TARGET_STRUCT_ID ON SIX_TARGET (SIX_STRUCT_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists3
               FROM USER_INDEXES
              WHERE UPPER(INDEX_NAME) = 'IDX_SIX_TARGET_OPT_ID';
          IF v_index_exists3 = 0 THEN
              EXECUTE IMMEDIATE
              'CREATE INDEX IDX_SIX_TARGET_OPT_ID ON SIX_TARGET (SIX_OPT_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists4
               FROM USER_INDEXES
              WHERE UPPER(INDEX_NAME) = 'IDX_SIX_TARGET_SANC_REGIME_LB';
          IF v_index_exists4 = 0 THEN
              EXECUTE IMMEDIATE
              'CREATE INDEX IDX_SIX_TARGET_SANC_REGIME_LB ON SIX_TARGET (TARGET, SANCTIONED, REGIME, LEGAL_BASIS)';
    END IF;

    BEGIN
        DBMS_STATS.GATHER_TABLE_STATS(
            ownname => USER,
            tabname => 'SIX_TARGET',
            estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,
            method_opt => 'FOR ALL COLUMNS SIZE AUTO',
            cascade => TRUE);
    END;
END;
/
