DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_index_exists1 NUMBER;
    v_index_exists2 NUMBER;
    v_index_exists3 NUMBER;

BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM USER_SEQUENCES
     WHERE UPPER(SEQUENCE_NAME) = 'SIX_STRUCTURED_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_STRUCTURED_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM USER_TABLES
     WHERE UPPER(TABLE_NAME) = 'SIX_STRUCTURED';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_STRUCTURED (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                LIST_ID                        NUMBER(19,0),
                VERSION_ID                     NUMBER(19,0),
                HOST_CH                        VARCHAR2(255 CHAR),
                HOST_ISIN                      VARCHAR2(255 CHAR),
                HOST_GK                        VARCHAR2(255 CHAR),
                HOST_ISSUER_SHORTNAME          VARCHAR2(255 CHAR),
                DESCRIPTION                    VARCHAR2(2000 CHAR),
                FISN                           VARCHAR2(255 CHAR),
                CONFIDENCE_LEVEL               VARCHAR2(255 CHAR),
                DATE_OPENED_IN_SIX             VARCHAR2(255 CHAR),
                SUBSTITUTE_ISSUE_DATE          VARCHAR2(255 CHAR),
                INDICATIVE_ISSUE_DATE          VARCHAR2(255 CHAR),
                SETTLEMENT_STYLE               VARCHAR2(255 CHAR),
                INSTRUMENT_TYPE                VARCHAR2(255 CHAR),
                DENOMINATION_CURRENCY          VARCHAR2(255 CHAR),
                MATURITY_DATE                  VARCHAR2(255 CHAR),
                ACTIVE_FLAG                    VARCHAR2(255 CHAR),
                ISSUE_DATE                     VARCHAR2(255 CHAR),
                UNDERLYING_CH                  VARCHAR2(255 CHAR),
                UNDERLYING_ISIN                VARCHAR2(255 CHAR),
                UNDERLYING_GK                  VARCHAR2(255 CHAR),
                UNDERLYING_ISSUER_SHORTNAME    VARCHAR2(255 CHAR),
                SEDOL                          VARCHAR2(255 CHAR),
                CUSIP                          VARCHAR2(255 CHAR),
                CINS                           VARCHAR2(255 CHAR),
                AUSTRIAN                       VARCHAR2(255 CHAR),
                BELGIAN                        VARCHAR2(255 CHAR),
                CANADIAN                       VARCHAR2(255 CHAR),
                GERMAN                         VARCHAR2(255 CHAR),
                DENMARK                        VARCHAR2(255 CHAR),
                FRANCE_RGA                     VARCHAR2(255 CHAR),
                FRANCE_EUROCLEAR               VARCHAR2(255 CHAR),
                ITALIAN                        VARCHAR2(255 CHAR),
                JAPANESE_CURRENT               VARCHAR2(255 CHAR),
                JAPANESE_NEW                   VARCHAR2(255 CHAR),
                LUXEMBOURG                     VARCHAR2(255 CHAR),
                NETHERLAND                     VARCHAR2(255 CHAR),
                NORWEGIAN                      VARCHAR2(255 CHAR),
                SWEDISH                        VARCHAR2(255 CHAR),
                XS_INT_NUMBER                  VARCHAR2(255 CHAR),
                PORTUGAL                       VARCHAR2(255 CHAR),
                SOUTH_KOREA                    VARCHAR2(255 CHAR),
                HONG_KONG                      VARCHAR2(255 CHAR),
                FIGI_GLOBAL_ID                 VARCHAR2(255 CHAR),
                FIGI_GLOBAL_SHARE_CLASS_ID     VARCHAR2(255 CHAR),
                REGIMES                        VARCHAR2(2000 CHAR),

                CONSTRAINT PK_SIX_STRUCTURED PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_STRUCTURED_LIST
                    FOREIGN KEY (LIST_ID)
                    REFERENCES REGLISS_LIST (ID),

                CONSTRAINT FK_SIX_STRUCTURED_VERSION
                    FOREIGN KEY (VERSION_ID)
                    REFERENCES VERSION (ID)
            )';
    END IF;

    SELECT COUNT(*) INTO v_index_exists1
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_STRUCTURE_LIST';
    IF v_index_exists1 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_STRUCTURE_LIST ON SIX_STRUCTURED (LIST_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists2
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_STRUCTURE_VERSION';
    IF v_index_exists2 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_STRUCTURE_VERSION ON SIX_STRUCTURED (VERSION_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists3
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_STRUCTURE_LIST_VER_ISIN_CON_ACT';
    IF v_index_exists3 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_STRUCTURE_LIST_VER_ISIN_CON_ACT ON SIX_STRUCTURED (LIST_ID, VERSION_ID, HOST_ISIN, CONFIDENCE_LEVEL, ACTIVE_FLAG)';
    END IF;

    BEGIN
        DBMS_STATS.GATHER_TABLE_STATS(
            ownname => USER,
            tabname => 'SIX_STRUCTURED',
            estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,
            method_opt => 'FOR ALL COLUMNS SIZE AUTO',
            cascade => TRUE);
    END;

END;
/
