DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_index_exists1 NUMBER;
    v_index_exists2 NUMBER;
    v_index_exists3 NUMBER;

BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_INSTRUMENTS_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_INSTRUMENTS_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_INSTRUMENTS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_INSTRUMENTS (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                LIST_ID                        NUMBER(19,0),
                VERSION_ID                     NUMBER(19,0),
                RECORD_ORIGIN                  VARCHAR2(255 CHAR),
                OLS_YES                        VARCHAR2(255 CHAR),
                OLS_NO                         VARCHAR2(255 CHAR),
                LINK_ENTITY                    VARCHAR2(255 CHAR),
                LINK_CSID                      VARCHAR2(255 CHAR),
                SANCTIONED_PARENT_ENTITY       VARCHAR2(255 CHAR),
                NAME_DIRECT_ISSUER             VARCHAR2(255 CHAR),
                CONFIDENCE_LEVEL               VARCHAR2(255 CHAR),
                ISIN                           VARCHAR2(255 CHAR),
                INSTR_NAME                     VARCHAR2(255 CHAR),
                FISN                           VARCHAR2(255 CHAR),
                CH_VALOR                       VARCHAR2(255 CHAR),
                INDICATIVE_ISSUE_DATE          VARCHAR2(255 CHAR),
                INSTRUMENT_TYPE                VARCHAR2(255 CHAR),
                SANCTION_RELEVANT_ASSET_CLASS  VARCHAR2(255 CHAR),
                MAIN_INSTRUMENT                VARCHAR2(255 CHAR),
                EQUITY_TYPE_OF_ISSUANCE        VARCHAR2(255 CHAR),
                DENOMINATION_CURRENCY          VARCHAR2(255 CHAR),
                MATURITY_DATE                  VARCHAR2(255 CHAR),
                DEBT_LIFETIME_IN_DAYS          VARCHAR2(255 CHAR),
                ACTIVE_FLAG                    VARCHAR2(255 CHAR),
                DATE_OPENED_IN_SIX             VARCHAR2(255 CHAR),
                SUBSTITUTE_ISSUE_DATE          VARCHAR2(255 CHAR),
                ISSUE_DATE                     VARCHAR2(255 CHAR),
                CAPITAL_CHANGE_DATE            VARCHAR2(255 CHAR),
                SEDOL                          VARCHAR2(255 CHAR),
                CUSIP                          VARCHAR2(255 CHAR),
                CINS                           VARCHAR2(255 CHAR),
                AUSTRIAN                       VARCHAR2(255 CHAR),
                BELGIAN                        VARCHAR2(255 CHAR),
                CANADIAN                       VARCHAR2(255 CHAR),
                GERMAN                         VARCHAR2(255 CHAR),
                DENMARK                        VARCHAR2(255 CHAR),
                FRANCE_RGA                     VARCHAR2(255 CHAR),
                FRANCE_EUROCLEAR               VARCHAR2(255 CHAR),
                ITALIAN                        VARCHAR2(255 CHAR),
                JAPANESE_CURRENT               VARCHAR2(255 CHAR),
                JAPANESE_NEW                   VARCHAR2(255 CHAR),
                LUXEMBOURG                     VARCHAR2(255 CHAR),
                NETHERLAND                     VARCHAR2(255 CHAR),
                NORWEGIAN                      VARCHAR2(255 CHAR),
                SWEDISH                        VARCHAR2(255 CHAR),
                XS_INT_NUMBER                  VARCHAR2(255 CHAR),
                PORTUGAL                       VARCHAR2(255 CHAR),
                SOUTH_KOREA                    VARCHAR2(255 CHAR),
                HONG_KONG                      VARCHAR2(255 CHAR),
                FIGI_GLOBAL_ID                 VARCHAR2(255 CHAR),
                FIGI_SHR_CLASS_LVL_ID          VARCHAR2(255 CHAR),
                OBLIGOR_ROLE                   VARCHAR2(255 CHAR),
                UNDERLYING_OBLIGOR             VARCHAR2(255 CHAR),
                UNDERLYING_OBLIGOR_GK          VARCHAR2(255 CHAR),
                REFERENCE_CAPITAL              VARCHAR2(255 CHAR),
                ACTUAL_CAPITAL                 VARCHAR2(255 CHAR),
                FIGI_GLOBAL_SHARE_CLASS_ID     VARCHAR2(255 CHAR),
                REGIMES                        VARCHAR2(2000 CHAR),

                CONSTRAINT PK_SIX_INSTRUMENT PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_INSTRUMENT_LIST
                FOREIGN KEY (LIST_ID)
                REFERENCES REGLISS_LIST (ID),

                CONSTRAINT FK_SIX_INSTRUMENT_VERSION
                FOREIGN KEY (VERSION_ID)
                REFERENCES VERSION (ID)
            )';
    END IF;

    SELECT COUNT(*) INTO v_index_exists1
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_INSTRUMENT_LIST';
    IF v_index_exists1 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_INSTRUMENT_LIST ON SIX_INSTRUMENTS (LIST_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists2
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_INSTRUMENT_VERSION';
    IF v_index_exists2 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_INSTRUMENT_VERSION ON SIX_INSTRUMENTS (VERSION_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists3
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_INSTRUMENT_LIST_VER_ISIN_CON_ACT';
    IF v_index_exists3 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_INSTRUMENT_LIST_VER_ISIN_CON_ACT ON SIX_INSTRUMENTS (LIST_ID, VERSION_ID, ISIN, CONFIDENCE_LEVEL, ACTIVE_FLAG)';
    END IF;

    BEGIN
        DBMS_STATS.GATHER_TABLE_STATS(
            ownname => USER,
            tabname => 'SIX_INSTRUMENTS',
            estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,
            method_opt => 'FOR ALL COLUMNS SIZE AUTO',
            cascade => TRUE);
    END;

END;
/
