DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_FILTERS_SEQ';
    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_FILTERS_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;
    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_FILTERS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_FILTERS (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                FILTER_NAME       VARCHAR2(255),
                FILTER_TAG        VARCHAR2(255),
                FILE_TYPE         VARCHAR2(255),
                LIST_ID           NUMBER(19),
                IS_ACTIVE         NUMBER(1)    DEFAULT 1,
                IS_DELETED        NUMBER(1)    DEFAULT 0,
                EXCLUDE_E014071   NUMBER(1)    DEFAULT 0,
                EXCLUDE_CMIC      NUMBER(1)    DEFAULT 0,

                CONSTRAINT PK_SIX_FILTERS     PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_FILTERS_LIST
                    FOREIGN KEY (LIST_ID)
                    REFERENCES REGLISS_LIST (ID)
            )';
    END IF;
END;
/
