DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_SUB_OR_FILTERS_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_SUB_OR_FILTERS_SEQ
                START WITH 1
                INCREMENT BY 1
                NOORDER
                NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_SUB_OR_FILTERS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_SUB_OR_FILTERS (
                ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                SIX_SUBFILTER_ID         NUMBER(19),
                SIX_SUB_OR_INDEX         NUMBER(19),
                FIELD_NAME               VARCHAR2(255),
                OPERATOR                 VARCHAR2(50),
                FILTER_VALUE             VARCHAR2(4000),
                IS_DELETED               NUMBER(1)    DEFAULT 0,

                CONSTRAINT PK_SIX_SUB_OR_FILTERS     PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_SUB_OR_SUBFILTER_ID
                    FOREIGN KEY (SIX_SUBFILTER_ID)
                    REFERENCES SIX_SUB_FILTERS (ID)
            )';
    END IF;
END;
/
