DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_FILTERED_POLLER_SEQ';
    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_FILTERED_POLLER_SEQ
             START WITH 1
             INCREMENT BY 1
             NOORDER
             NOCYCLE';
    END IF;
    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_FILTERED_POLLER';
    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_FILTERED_POLLER (
                        ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                         FILE_TYPE          VARCHAR2(255),
                         INSERTION_TIME     TIMESTAMP(6),
                         RAW_LIST_ID                NUMBER(10),
                         RAW_VERSION_ID             NUMBER(15),
                         SIX_LIST_REFERENCE         NUMBER(15),
                         BATCH_JOB_EXECUTION_ID     NUMBER(15),
                         CONSTRAINT PK_SIX_FILTERED_POLLER   PRIMARY KEY (ID)

        )';
    END IF;
END;
/
