DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_index_exists1 NUMBER;
    v_index_exists2 NUMBER;
    v_index_exists3 NUMBER;

BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM USER_SEQUENCES
     WHERE UPPER(SEQUENCE_NAME) = 'SIX_OPTION_SEQ';

    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE SEQUENCE "SIX_OPTION_SEQ"
            START WITH 1
            INCREMENT BY 1
            NOORDER NOCYCLE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
      FROM USER_TABLES
     WHERE UPPER(TABLE_NAME) = 'SIX_OPTION';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_OPTION
            (   ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                LIST_ID                        NUMBER(19,0),
                VERSION_ID                     NUMBER(19,0),
                CH_OPTION                      VARCHAR2(255 CHAR),
                ISIN_OPTION                    VARCHAR2(255 CHAR),
                DESCRIPTION                    VARCHAR2(2000 CHAR),
                FISN                           VARCHAR2(255 CHAR),
                ISSUER_GK                      VARCHAR2(255 CHAR),
                ISSUER_NAME                    VARCHAR2(255 CHAR),
                CONFIDENCE_LEVEL               VARCHAR2(255 CHAR),
                DATE_OPENED_IN_SIX             VARCHAR2(255 CHAR),
                EXPIRY_DATE                    VARCHAR2(255 CHAR),
                INSTRUMENT_TYPE                VARCHAR2(255 CHAR),
                DENOMINATION_CURRENCY          VARCHAR2(255 CHAR),
                ACTIVE_FLAG                    VARCHAR2(255 CHAR),
                ISSUE_DATE                     VARCHAR2(255 CHAR),
                UNDERLYING_CH                  VARCHAR2(255 CHAR),
                UNDERLYING_ISIN                VARCHAR2(255 CHAR),
                UNDERLYING_ISSUER_GK           VARCHAR2(255 CHAR),
                UNDERLYING_ISSUER_NAME         VARCHAR2(255 CHAR),
                SEDOL                          VARCHAR2(255 CHAR),
                CUSIP                          VARCHAR2(255 CHAR),
                CINS                           VARCHAR2(255 CHAR),
                AUSTRIAN                       VARCHAR2(255 CHAR),
                BELGIAN                        VARCHAR2(255 CHAR),
                CANADIAN                       VARCHAR2(255 CHAR),
                GERMAN                         VARCHAR2(255 CHAR),
                DENMARK                        VARCHAR2(255 CHAR),
                FRANCE_RGA                     VARCHAR2(255 CHAR),
                FRANCE_EUROCLEAR               VARCHAR2(255 CHAR),
                ITALIAN                        VARCHAR2(255 CHAR),
                JAPANESE_CURRENT               VARCHAR2(255 CHAR),
                JAPANESE_NEW                   VARCHAR2(255 CHAR),
                LUXEMBOURG                     VARCHAR2(255 CHAR),
                NETHERLAND                     VARCHAR2(255 CHAR),
                NORWEGIAN                      VARCHAR2(255 CHAR),
                SWEDISH                        VARCHAR2(255 CHAR),
                XS_INT_NUMBER                  VARCHAR2(255 CHAR),
                PORTUGAL                       VARCHAR2(255 CHAR),
                SOUTH_KOREA                    VARCHAR2(255 CHAR),
                HONG_KONG                      VARCHAR2(255 CHAR),
                FIGI_GLOBAL_ID                 VARCHAR2(255 CHAR),
                FIGI_GLOBAL_SHARE_CLASS_ID     VARCHAR2(255 CHAR),
                REGIMES                        VARCHAR2(2000 CHAR),

                CONSTRAINT PK_SIX_OPTION PRIMARY KEY (ID),

                CONSTRAINT FK_SIX_OPTION_LIST
                    FOREIGN KEY (LIST_ID)
                    REFERENCES REGLISS_LIST (ID),

                CONSTRAINT FK_SIX_OPTION_VERSION
                    FOREIGN KEY (VERSION_ID)
                    REFERENCES VERSION (ID)
            )';
    END IF;

    SELECT COUNT(*) INTO v_index_exists1
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_OPT_LIST';
    IF v_index_exists1 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_OPT_LIST ON SIX_OPTION (LIST_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists2
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_OPT_VERSION';
    IF v_index_exists2 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_OPT_VERSION ON SIX_OPTION (VERSION_ID)';
    END IF;

    SELECT COUNT(*) INTO v_index_exists3
      FROM USER_INDEXES
     WHERE UPPER(INDEX_NAME) = 'IDX_SIX_OPT_LIST_VER_ISIN_CON_ACT';
    IF v_index_exists3 = 0 THEN
        EXECUTE IMMEDIATE
        'CREATE INDEX IDX_SIX_OPT_LIST_VER_ISIN_CON_ACT ON SIX_OPTION (LIST_ID, VERSION_ID, ISIN_OPTION, CONFIDENCE_LEVEL, ACTIVE_FLAG)';
    END IF;

    BEGIN
        DBMS_STATS.GATHER_TABLE_STATS(
            ownname => USER,
            tabname => 'SIX_OPTION',
            estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,
            method_opt => 'FOR ALL COLUMNS SIZE AUTO',
            cascade => TRUE);
    END;

END;
/
