package com.bnpp.regliss.importer.six.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import javax.annotation.PostConstruct;
import javax.persistence.Column;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.regex.Pattern;

// TODO: re-add project import for: ReglissBatchProfile

/**
 * Writes SIX raw rows (SIX_INSTRUMENTS / SIX_STRUCTURED / SIX_OPTION + SIX_TARGET)
 * with plain JDBC batch INSERTs.
 *
 * WHY: the entities use GenerationType.IDENTITY. With IDENTITY, Hibernate must send
 * every INSERT on its own to read the generated id back, so JPA can never batch these
 * tables: 1 lakh parents + their targets = several lakh single-row round trips per file.
 *
 * HOW:
 *  - Ids come from the table's OWN identity sequence (the ISEQ$$_nnn sequence Oracle
 *    created for "ID ... GENERATED BY DEFAULT AS IDENTITY"). One query per batch:
 *        SELECT "OWNER"."ISEQ$$_nnn".NEXTVAL FROM DUAL CONNECT BY LEVEL <= 1000
 *    Same sequence Oracle uses itself, so ids can never collide with rows inserted any
 *    other way, and no new sequence or table is needed.
 *  - Parent ids are known before the INSERT, so the SIX_TARGET children are batched too.
 *  - Parents + children of one batch commit together in a NEW transaction: a failed batch
 *    leaves nothing half-written.
 *  - The INSERT column list is read once per entity class from its existing JPA
 *    annotations (@Table, @Column, @JoinColumn). Entities are NOT changed. If a field
 *    cannot be mapped the writer stops with a clear message instead of skipping a column.
 */
@Component
@ReglissBatchProfile
@Slf4j
public class SixJdbcBulkWriter {

    private static final Pattern SQL_NAME = Pattern.compile("^[A-Z][A-Z0-9_$#]{0,127}$");

    /** Max rows per executeBatch() round trip (children can outnumber parents). */
    private static final int JDBC_CHUNK = 1000;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PlatformTransactionManager transactionManager;

    @Autowired
    private Environment environment;

    private TransactionTemplate newTx;

    private final Map<Class<?>, TableMapping> mappings = new ConcurrentHashMap<>();
    private final Map<String, String> idSequences = new ConcurrentHashMap<>();

    @PostConstruct
    void init() {
        newTx = new TransactionTemplate(transactionManager);
        newTx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    }

    /**
     * Inserts one batch of parents and all their SIX_TARGET children in one new transaction.
     *
     * @param parents       mapped entities of one batch (InstrumentFile / StructuredFile / OptionsFile)
     * @param listId        LIST_ID of every parent
     * @param versionId     VERSION_ID of every parent
     * @param childrenOf    e.g. InstrumentFile::getSixTargets
     * @param childFkColumn SIX_TARGET column pointing to the parent: SIX_INSTRU_ID / SIX_STRUCT_ID / SIX_OPT_ID
     * @return number of SIX_TARGET rows written
     */
    public <P> int insertBatch(List<P> parents, long listId, long versionId,
                               Function<P, ? extends Collection<?>> childrenOf, String childFkColumn) {
        if (parents.isEmpty()) {
            return 0;
        }
        final TableMapping parentMap = mappingFor(parents.get(0).getClass());

        final List<Object> children = new ArrayList<>();
        final List<P> childParent = new ArrayList<>();
        for (P parent : parents) {
            Collection<?> kids = childrenOf.apply(parent);
            if (kids != null) {
                for (Object kid : kids) {
                    if (kid != null) {
                        children.add(kid);
                        childParent.add(parent);
                    }
                }
            }
        }
        final TableMapping childMap = children.isEmpty() ? null : mappingFor(children.get(0).getClass());
        final String parentSeq = idSequenceFor(parentMap.table);
        final String childSeq = childMap == null ? null : idSequenceFor(childMap.table);

        Integer written = newTx.execute(status -> {
            // 1. parent ids + parent rows (LIST_ID / VERSION_ID forced to this import's values)
            List<Long> parentIds = nextIds(parentSeq, parents.size());
            Map<Object, Long> idByParent = new IdentityHashMap<>(parents.size() * 2);
            for (int i = 0; i < parents.size(); i++) {
                parentMap.setId(parents.get(i), parentIds.get(i));
                idByParent.put(parents.get(i), parentIds.get(i));
            }
            batchInsert(parentMap, parents, parentIds, (row, col) ->
                    "LIST_ID".equals(col) ? (Object) listId : "VERSION_ID".equals(col) ? (Object) versionId : null);

            // 2. child ids + child rows, FK set from the parent id
            if (childMap != null) {
                List<Long> childIds = nextIds(childSeq, children.size());
                List<Long> fk = new ArrayList<>(children.size());
                for (int i = 0; i < children.size(); i++) {
                    childMap.setId(children.get(i), childIds.get(i));
                    fk.add(idByParent.get(childParent.get(i)));
                }
                batchInsert(childMap, children, childIds, (row, col) -> childFkColumn.equals(col) ? fk.get(row) : null);
            }
            return children.size();
        });
        return written == null ? 0 : written;
    }

    /**
     * Removes every row of one version (SIX_TARGET rows go with them: ON DELETE CASCADE in V2_470).
     * Used when an import fails, so no half-loaded version is left behind.
     */
    public int deleteVersion(Class<?> parentEntity, long versionId) {
        String table = mappingFor(parentEntity).table;
        Integer n = newTx.execute(status ->
                jdbcTemplate.update("DELETE FROM " + table + " WHERE VERSION_ID = ?", versionId));
        return n == null ? 0 : n;
    }

    // ------------------------------------------------------------------ internals

    /** Returns a value that replaces the entity field for this row/column, or null to use the field. */
    private interface RowValues {
        Object valueFor(int row, String column);
    }

    private void batchInsert(TableMapping map, List<?> rows, List<Long> ids, RowValues forced) {
        for (int from = 0; from < rows.size(); from += JDBC_CHUNK) {
            final int start = from;
            final int end = Math.min(from + JDBC_CHUNK, rows.size());
            jdbcTemplate.batchUpdate(map.insertSql, new BatchPreparedStatementSetter() {
                @Override
                public void setValues(PreparedStatement ps, int i) throws SQLException {
                    int row = start + i;
                    Object entity = rows.get(row);
                    ps.setLong(1, ids.get(row));
                    int p = 2;
                    for (ColumnMapping c : map.columns) {
                        Object value = forced.valueFor(row, c.column);
                        if (value != null) {
                            ps.setLong(p++, ((Number) value).longValue());
                        } else {
                            c.bind(ps, p++, entity);
                        }
                    }
                }

                @Override
                public int getBatchSize() {
                    return end - start;
                }
            });
        }
    }

    private List<Long> nextIds(String sequence, int count) {
        List<Long> ids = jdbcTemplate.queryForList(
                "SELECT " + sequence + ".NEXTVAL FROM DUAL CONNECT BY LEVEL <= ?", Long.class, count);
        if (ids.size() != count) {
            throw new IllegalStateException(sequence + " returned " + ids.size() + " ids, expected " + count);
        }
        return ids;
    }

    /**
     * The table's identity sequence, e.g. "REGLISS"."ISEQ$$_91833". Looked up once.
     * Override with six.import.id-sequence.<TABLE>=OWNER.SEQ_NAME if the application
     * user is not the table owner (synonyms).
     */
    private String idSequenceFor(String table) {
        return idSequences.computeIfAbsent(table, t -> {
            String override = environment.getProperty("six.import.id-sequence." + t);
            if (override != null && !override.trim().isEmpty()) {
                return qualified(override.trim().toUpperCase());
            }
            List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                    "SELECT OWNER, SEQUENCE_NAME FROM ALL_TAB_IDENTITY_COLUMNS" +
                    " WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AND TABLE_NAME = ? AND COLUMN_NAME = 'ID'", t);
            if (rows.size() != 1) {
                throw new IllegalStateException("No identity sequence found for " + t + ".ID in the current schema;"
                        + " set six.import.id-sequence." + t + "=OWNER.SEQUENCE_NAME");
            }
            String seq = qualified(rows.get(0).get("OWNER") + "." + rows.get(0).get("SEQUENCE_NAME"));
            log.info("SIX import: {} ids come from {}", t, seq);
            return seq;
        });
    }

    private static String qualified(String ownerDotName) {
        String[] parts = ownerDotName.split("\\.");
        StringBuilder sb = new StringBuilder();
        for (String part : parts) {
            if (!SQL_NAME.matcher(part).matches()) {
                throw new IllegalArgumentException("Bad sequence name: " + ownerDotName);
            }
            sb.append(sb.length() == 0 ? "" : ".").append('"').append(part).append('"');
        }
        return sb.toString();
    }

    private TableMapping mappingFor(Class<?> type) {
        return mappings.computeIfAbsent(type, TableMapping::new);
    }

    /** Column list + INSERT statement for one entity class, built once from its JPA annotations. */
    static final class TableMapping {
        final String table;
        final Field idField;
        final List<ColumnMapping> columns = new ArrayList<>();
        final String insertSql;

        TableMapping(Class<?> type) {
            Table t = type.getAnnotation(Table.class);
            if (t == null || t.name().isEmpty()) {
                throw new IllegalStateException(type.getName() + " has no @Table(name=...)");
            }
            this.table = t.name().toUpperCase();

            Field id = null;
            List<Class<?>> hierarchy = new ArrayList<>();
            for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
                hierarchy.add(c);
            }
            Collections.reverse(hierarchy);
            for (Class<?> c : hierarchy) {
                for (Field f : c.getDeclaredFields()) {
                    int mod = f.getModifiers();
                    if (Modifier.isStatic(mod) || Modifier.isTransient(mod) || f.isSynthetic()
                            || f.isAnnotationPresent(Transient.class)
                            || f.isAnnotationPresent(OneToMany.class)
                            || f.isAnnotationPresent(ManyToMany.class)) {
                        continue;
                    }
                    f.setAccessible(true);
                    if (f.isAnnotationPresent(Id.class)) {
                        id = f;
                        continue;
                    }
                    Column col = f.getAnnotation(Column.class);
                    JoinColumn join = f.getAnnotation(JoinColumn.class);
                    boolean relation = f.isAnnotationPresent(ManyToOne.class) || f.isAnnotationPresent(OneToOne.class);
                    if (col != null) {
                        if (col.insertable()) columns.add(new ColumnMapping(name(col.name(), f), f, false));
                    } else if (relation && join != null) {
                        if (join.insertable()) columns.add(new ColumnMapping(name(join.name(), f), f, true));
                    } else {
                        throw new IllegalStateException("Cannot map " + c.getSimpleName() + "." + f.getName()
                                + " for insert into " + table + ": add @Column(name=...) or @Transient");
                    }
                }
            }
            if (id == null) {
                throw new IllegalStateException(type.getName() + " has no @Id field");
            }
            this.idField = id;

            StringBuilder cols = new StringBuilder("ID");
            StringBuilder qs = new StringBuilder("?");
            for (ColumnMapping c : columns) {
                cols.append(", ").append(c.column);
                qs.append(", ?");
            }
            this.insertSql = "INSERT INTO " + table + " (" + cols + ") VALUES (" + qs + ")";
            log.info("SIX import: {} -> {} ({} columns)", type.getSimpleName(), table, columns.size() + 1);
        }

        void setId(Object entity, Long id) {
            try {
                idField.set(entity, id);
            } catch (IllegalAccessException e) {
                throw new IllegalStateException(e);
            }
        }

        private static String name(String annotated, Field f) {
            String n = (annotated == null || annotated.isEmpty()) ? f.getName() : annotated;
            n = n.replace("\"", "").toUpperCase();
            if (!SQL_NAME.matcher(n).matches()) {
                throw new IllegalStateException("Unsupported column name '" + n + "' on field " + f.getName());
            }
            return n;
        }
    }

    /** Reads one field and binds it with a stable JDBC type (keeps Oracle batches from splitting). */
    static final class ColumnMapping {
        final String column;
        final Field field;
        final boolean foreignKey;
        final EnumType enumType;
        private volatile Method idGetter;

        ColumnMapping(String column, Field field, boolean foreignKey) {
            this.column = column;
            this.field = field;
            this.foreignKey = foreignKey;
            Enumerated en = field.getAnnotation(Enumerated.class);
            this.enumType = en == null ? EnumType.ORDINAL : en.value();
        }

        void bind(PreparedStatement ps, int pos, Object entity) throws SQLException {
            Object value;
            try {
                value = field.get(entity);
            } catch (IllegalAccessException e) {
                throw new SQLException("Cannot read " + field.getName(), e);
            }
            if (foreignKey) {
                Long id = value == null ? null : idOf(value);
                if (id == null) ps.setNull(pos, Types.NUMERIC); else ps.setLong(pos, id);
            } else if (value == null) {
                ps.setNull(pos, sqlType(field.getType()));
            } else if (value instanceof String) {
                ps.setString(pos, (String) value);
            } else if (value instanceof Enum) {
                Enum<?> e = (Enum<?>) value;
                if (enumType == EnumType.STRING) ps.setString(pos, e.name()); else ps.setInt(pos, e.ordinal());
            } else if (value instanceof Boolean) {
                ps.setInt(pos, ((Boolean) value) ? 1 : 0);
            } else if (value instanceof java.util.Date && !(value instanceof java.sql.Date)) {
                ps.setTimestamp(pos, new Timestamp(((java.util.Date) value).getTime()));
            } else {
                ps.setObject(pos, value);
            }
        }

        private Long idOf(Object related) throws SQLException {
            try {
                Method m = idGetter;
                if (m == null) {
                    m = field.getType().getMethod("getId");   // declared type: works for Hibernate proxies too
                    idGetter = m;
                }
                Object id = m.invoke(related);
                return id == null ? null : ((Number) id).longValue();
            } catch (ReflectiveOperationException e) {
                throw new SQLException("Cannot read id of " + related.getClass().getName() + " for " + column, e);
            }
        }

        private static int sqlType(Class<?> t) {
            if (t == String.class || t.isEnum()) return Types.VARCHAR;
            if (Number.class.isAssignableFrom(t) || t == Boolean.class) return Types.NUMERIC;
            if (java.util.Date.class.isAssignableFrom(t) || t.getName().startsWith("java.time.")) return Types.TIMESTAMP;
            return Types.VARCHAR;
        }
    }
}
