DECLARE
    v_seq_exists   NUMBER;
    v_table_exists NUMBER;
    v_idx_exists   NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_seq_exists
      FROM user_sequences
     WHERE UPPER(sequence_name) = 'SIX_FILTERED_POLLER_SEQ';
    IF v_seq_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SIX_FILTERED_POLLER_SEQ
             START WITH 1
             INCREMENT BY 1
             NOORDER
             NOCYCLE';
    END IF;
    SELECT COUNT(*) INTO v_table_exists
      FROM user_tables
     WHERE UPPER(table_name) = 'SIX_FILTERED_POLLER';
    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE SIX_FILTERED_POLLER (
                        ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                         FILE_TYPE          VARCHAR2(255),
                         INSERTION_TIME     TIMESTAMP(6),
                         RAW_LIST_ID                NUMBER(10),
                         RAW_VERSION_ID             NUMBER(15),
                         SIX_LIST_REFERENCE         NUMBER(15),
                         BATCH_JOB_EXECUTION_ID     NUMBER(15),
                         STATUS                     VARCHAR2(20 CHAR),
                         UPDATED_TIME               TIMESTAMP(6),
                         GENERATION_REASON          VARCHAR2(20 CHAR),
                         CONSTRAINT PK_SIX_FILTERED_POLLER   PRIMARY KEY (ID)

        )';
    END IF;
    -- export phase 1: the claim and the release read the rows by STATUS (and list) every minute on both servers
    SELECT COUNT(*) INTO v_idx_exists
      FROM user_indexes
     WHERE UPPER(index_name) = 'IDX_SFP_STATUS_LIST';
    IF v_idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SFP_STATUS_LIST ON SIX_FILTERED_POLLER (STATUS, SIX_LIST_REFERENCE)';
    END IF;
END;
/
